### ISSUE TITLE
HTML Style and Indentation

### ISSUE THREAD

**Issue by jordanwillis** [ThomasRipplinger/14ColmarAcademy#1]
From a purely style perspective, your HTML is looking really good!  Watch out for cases where your indentation breaks down due to editor reasons (or some other reason).  For example...

https://github.com/ThomasRipplinger/14ColmarAcademy/blob/master/index.html#L67

This all just does toward making your code as readable as possible which is super important the larger the project gets and the more people that are involved.

**Comment by tomripp** [comment]
ok, thanks for the comment, fixed it
