### ISSUE TITLE
Line breaks in HTML

### ISSUE THREAD

**Issue by jordanwillis** [ThomasRipplinger/14ColmarAcademy#2]
As I was reviewing your code I stumbled upon a few instances of line break usage (`<br/>`).

https://github.com/ThomasRipplinger/14ColmarAcademy/blob/master/index.html#L39
https://github.com/ThomasRipplinger/14ColmarAcademy/blob/master/index.html#L41
https://github.com/ThomasRipplinger/14ColmarAcademy/blob/master/index.html#L51

While it is often convent to use line breaks to quickly fix spacing, sizing, or alignment issues, I would recommend that you shy away from using line breaks and handle this sort of thing directly in your CSS.  As you will continue learning and practicing in BWS, we want our HTML to be as semantic as possible and line breaks takes away from that.

Some things that you can do instead is of using <br/>` is add extra margin or padding properties to your CSS or tweaking some of your flexbox related properties.

**Comment by tomripp** [comment]
ok, understood, I've fixed it
