### ISSUE TITLE
alt Attributes

### ISSUE THREAD

**Issue by jordanwillis** [ThomasRipplinger/14ColmarAcademy#4]
Also, be sure to always include the `alt` attribute in your image tags to help make sure you page is following common accessibility rules.  This is one of the easiest accessibility rules to implement but is just one of many things that we can do to make sure pages are `a11y` compliant.

https://a11yproject.com/checklist

**Comment by tomripp** [comment]
Thx for the link, this is helpful. I meanwhile added the alt, this was in the next lesson of the course
